/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cl.fernando.pnb.gui;

import java.awt.Image;
import javax.swing.ImageIcon;
import javax.imageio.ImageIO;
import java.io.IOException;
import java.lang.Math; // Necesario para Math.min

/**
 *
 * @author ferna
 */
public class LoginFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(LoginFrame.class.getName());

    /**
     * Creates new form LoginFrame
     */
    public LoginFrame() {
        initComponents();
        
        this.setLocationRelativeTo(null);
        
    // Agrega el Listener para detectar cuando el lblLogo tiene tamaño (para escalado)
    lblLogo.addComponentListener(new java.awt.event.ComponentAdapter() {
        @Override
        public void componentResized(java.awt.event.ComponentEvent e) {
            adjustImageToLabel();
        }
    });
    // Llamada inicial
    adjustImageToLabel();
        
    }
    
    private void adjustImageToLabel() {
    try {
        Image originalImage = ImageIO.read(getClass().getResource("/resources/icons/logo.jpg")); 

        // Obtener el tamaño del JLabel (o usar los valores predeterminados)
        int desiredWidth = lblLogo.getWidth();
        int desiredHeight = lblLogo.getHeight();

        if (desiredWidth <= 0) desiredWidth = 426; 
        if (desiredHeight <= 0) desiredHeight = 94; 

        // --- CÓDIGO MODIFICADO PARA MODO COVER ---
        // 1. Calcular los factores de escala para ancho y alto
        double scaleX = (double) desiredWidth / originalImage.getWidth(null);
        double scaleY = (double) desiredHeight / originalImage.getHeight(null);

        // 2. Usar el factor de escala MÁS GRANDE (Math.max) para asegurar que la imagen
        //    llene completamente el área visible, aceptando el recorte en el otro eje.
        double scale = Math.max(scaleX, scaleY); 

        // 3. Calcular las nuevas dimensiones
        int newWidth = (int) (originalImage.getWidth(null) * scale);
        int newHeight = (int) (originalImage.getHeight(null) * scale);
        // ---------------------------------------------

        // Escalar y asignar
        // La imagen escalada será más grande que el lblLogo, pero el lblLogo solo mostrará el centro.
        Image scaledImage = originalImage.getScaledInstance(newWidth, newHeight, Image.SCALE_SMOOTH);
        lblLogo.setIcon(new ImageIcon(scaledImage));
        
        // El centrado es crucial para que el recorte sea simétrico (centrado)
        lblLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLogo.setVerticalAlignment(javax.swing.SwingConstants.CENTER);

    } catch (IOException e) { 
        System.err.println("Error al cargar o escalar la imagen: " + e.getMessage());
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Título = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        txtPass = new javax.swing.JPasswordField();
        btnIniciar = new javax.swing.JButton();
        contrasenia = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lblLogo = new javax.swing.JLabel();
        btnSalir = new javax.swing.JButton();
        usuario = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Título.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        Título.setForeground(new java.awt.Color(102, 204, 255));
        Título.setText("Pixel & Bean – Sistema de Gestión");
        jPanel1.add(Título, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 12, -1, -1));
        jPanel1.add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 220, 100, -1));

        txtPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPassActionPerformed(evt);
            }
        });
        jPanel1.add(txtPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 270, 100, -1));

        btnIniciar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnIniciar.setText("Iniciar sesión");
        btnIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarActionPerformed(evt);
            }
        });
        jPanel1.add(btnIniciar, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 291, -1, -1));

        contrasenia.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        contrasenia.setText("Contraseña:");
        jPanel1.add(contrasenia, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 250, -1, -1));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons/logo.jpg"))); // NOI18N
        lblLogo.setToolTipText("");
        jPanel2.add(lblLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 440, 140));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 45, 440, 140));

        btnSalir.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        jPanel1.add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(308, 291, 90, -1));

        usuario.setBackground(new java.awt.Color(255, 255, 255));
        usuario.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        usuario.setText("Usuario:");
        jPanel1.add(usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 200, 60, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 332, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
        
        this.dispose();
        
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarActionPerformed
        // TODO add your handling code here:
        String user = txtUsuario.getText();
        String pass = new String(txtPass.getPassword());
        String usuarioCorrecto = "admin";
        String contraseniaCorrecta = "1234";
        
        if (user.equals(usuarioCorrecto) && pass.equals(contraseniaCorrecta)) {
        javax.swing.JOptionPane.showMessageDialog(this, "¡Bienvenido, " + user + "!", "Inicio de Sesión", javax.swing.JOptionPane.INFORMATION_MESSAGE);   
        
            MainFrame principal = new MainFrame();
            principal.setVisible(true);
            this.dispose();
                    
    } else {
    
        javax.swing.JOptionPane.showMessageDialog(this, "Usuario o Contraseña incorrectos.", "Error de Sesión", javax.swing.JOptionPane.ERROR_MESSAGE);
        
      
    }
        
        
        
    }//GEN-LAST:event_btnIniciarActionPerformed

    private void txtPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPassActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Título;
    private javax.swing.JButton btnIniciar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel contrasenia;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JPasswordField txtPass;
    private javax.swing.JTextField txtUsuario;
    private javax.swing.JLabel usuario;
    // End of variables declaration//GEN-END:variables
}
